### ISSUE TITLE
bug都能写出一堆一堆的，怎么拿这么多star的?

### ISSUE THREAD

**Issue by luozantu** [fluttercandies/wechat_flutter#25]

**Comment by ahyangnb** [comment]
对标flutter环境哦，如果产生其他依赖无法编译的问题，可以尝试将pubspec.yaml中的dependencies中的所有依赖的"^"去掉，重新编译尝试。 还是出错的话在项目主目录执行flutter clean再重新运行。 如果出现插件版本不适配记得看pubspec.yaml文件介绍的插件flutter版本是否与自己本地Flutter适配。
