### ISSUE TITLE
代码没报错，但是flutter run 报错

### ISSUE THREAD

**Issue by diaowenyang** [fluttercandies/wechat_flutter#30]
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_field-4.0.0/lib/src/extended_editable_text.dart:1017:7: Error: The non-abstract class 'ExtendedEditableTextState' is missing implementations for these members:
 - TextInputClient.performPrivateCommand                                
Try to either                                                           
 - provide an implementation,                                           
 - inherit an implementation from a superclass or mixin,                
 - mark the class as abstract, or                                       
 - provide a 'noSuchMethod' implementation.                             
                                                                        
class ExtendedEditableTextState extends State<ExtendedEditableText>     
      ^^^^^^^^^^^^^^^^^^^^^^^^^                                         
../../Downloads/flutter/packages/flutter/lib/src/services/text_input.dart:813:8: Context: 'TextInputClient.performPrivateCommand' is defined here.
  void performPrivateCommand(String action, Map<String, dynamic> data); 
       ^^^^^^^^^^^^^^^^^^^^^                                            
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text-4.0.0/lib/src/extended_render_paragraph.dart:21:7: Error: The non-abstract class 'ExtendedRenderParagraph' is missing implementations for these members:
 - ExtendedTextSelectionRenderObject.caretPrototype                     
 - ExtendedTextSelectionRenderObject.textSelectionDelegate              
Try to either                                                           
 - provide an implementation,                                           
 - inherit an implementation from a superclass or mixin,                
 - mark the class as abstract, or                                       
 - provide a 'noSuchMethod' implementation.                             
                                                                        
class ExtendedRenderParagraph extends ExtendedTextSelectionRenderObject {
      ^^^^^^^^^^^^^^^^^^^^^^^                                           
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_library-4.0.3/lib/src/render_object/extended_text_selection_render_object.dart:376:12: Context: 'ExtendedTextSelectionRenderObject.caretPrototype' is defined here.
  Rect get caretPrototype;                                              
           ^^^^^^^^^^^^^^                                               
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_library-4.0.3/lib/src/render_object/extended_text_selection_render_object.dart:383:29: Context: 'ExtendedTextSelectionRenderObject.textSelectionDelegate' is defined here.
  TextSelectionDelegate get textSelectionDelegate;                      
                            ^^^^^^^^^^^^^^^^^^^^^                       
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_field-4.0.0/lib/src/extended_render_editable.dart:99:7: Error: The non-abstract class 'ExtendedRenderEditable' is missing implementations for these members:
 - ExtendedTextSelectionRenderObject.caretPrototype                     
Try to either                                                           
 - provide an implementation,                                           
 - inherit an implementation from a superclass or mixin,                
 - mark the class as abstract, or                                       
 - provide a 'noSuchMethod' implementation.                             
                                                                        
class ExtendedRenderEditable extends ExtendedTextSelectionRenderObject {
      ^^^^^^^^^^^^^^^^^^^^^^                                            
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_library-4.0.3/lib/src/render_object/extended_text_selection_render_object.dart:376:12: Context: 'ExtendedTextSelectionRenderObject.caretPrototype' is defined here.
  Rect get caretPrototype;                                              
           ^^^^^^^^^^^^^^                                               
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text-4.0.0/lib/src/extended_render_paragraph.dart:1026:9: Error: No named parameter with the name 'handleSpecialText'.
        handleSpecialText: handleSpecialText,                           
        ^^^^^^^^^^^^^^^^^                                               
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text-4.0.0/lib/src/extended_render_paragraph.dart:1241:7: Error: No named parameter with the name 'handleSpecialText'.
      handleSpecialText: handleSpecialText,                             
      ^^^^^^^^^^^^^^^^^                                                 
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text-4.0.0/lib/src/extended_render_paragraph.dart:1258:7: Error: No named parameter with the name 'handleSpecialText'.
      handleSpecialText: handleSpecialText,                             
      ^^^^^^^^^^^^^^^^^                                                 
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_field-4.0.0/lib/src/extended_render_editable.dart:377:7: Error: No named parameter with the name 'handleSpecialText'.
      handleSpecialText: handleSpecialText,                             
      ^^^^^^^^^^^^^^^^^                                                 
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_field-4.0.0/lib/src/extended_render_editable.dart:396:7: Error: No named parameter with the name 'handleSpecialText'.
      handleSpecialText: handleSpecialText,                             
      ^^^^^^^^^^^^^^^^^                                                 
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_field-4.0.0/lib/src/extended_render_editable.dart:1619:9: Error: No named parameter with the name 'handleSpecialText'.
        handleSpecialText: handleSpecialText,                           
        ^^^^^^^^^^^^^^^^^                                               
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_field-4.0.0/lib/src/extended_render_editable.dart:1925:7: Error: No named parameter with the name 'handleSpecialText'.
      handleSpecialText: handleSpecialText,                             
      ^^^^^^^^^^^^^^^^^                                                 
                                                                        
                                                                        
FAILURE: Build failed with an exception.

**Comment by huiqiangyang** [comment]
![Uploading image.png…]()

**Comment by diaowenyang** [comment]
果然可以，谢谢。
