### ISSUE TITLE
添加好友-UI异常

### ISSUE THREAD

**Issue by sunsetroads** [fluttercandies/wechat_flutter#36]
![Simulator Screen Shot - iPhone 11 - 2021-07-28 at 16 58 09](https://user-images.githubusercontent.com/27948513/127294789-b33025ca-2c32-44db-a824-a24c10fbd48f.png)

**Comment by yendiscart** [comment]
What backend do you use to store data or run as admin for this project?

**Comment by fodedoumbouya** [comment]
> What backend do you use to store data or run as admin for this project?
They best way is to create a API and send the request to the API which can access to your database and you just store logIn needed data on local

**Comment by Nomeleel** [comment]
Fixed[#36](https://github.com/fluttercandies/wechat_flutter/commit/966162576bf11bd5b1c277b28f860f3996837fcf)
