### ISSUE TITLE
Flutter 2.5.2 Xcode 13.3.1 ，app无法运行

### ISSUE THREAD

**Issue by GarthGit** [fluttercandies/wechat_flutter#47]
Could not build the application for the simulator.
Error launching application on iPhone 13.

The iOS Simulator deployment target ‘IPHONEOS_DEPLOYMENT_TARGET‘ is set to 8.0, but the range...9.0--

**Comment by GarthGit** [comment]
在podfile中设置一下命令，继续提示错误 YYModel 中一些
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end

 1 warning generated.
    ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/yinjiangtao/Downloads/wechat_flutter-master/ios/Pods/TXIMSDK_iOS/ImSDK.framework/ImSDK' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

**Comment by helloMrTom** [comment]
> 在podfile中设置一下命令，继续提示错误 YYModel 中一些 post_install do |installer| installer.pods_project.targets.each do |target| flutter_additional_ios_build_settings(target) target.build_configurations.each do |config| config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0' end end end
> 
> 1 warning generated. ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/yinjiangtao/Downloads/wechat_flutter-master/ios/Pods/TXIMSDK_iOS/ImSDK.framework/ImSDK' for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation) note: Using new build system note: Planning note: Build preparation complete note: Building targets in dependency order





Error (Xcode): Building for iOS Simulator, but linking in dylib built for iOS, file '/Volumes/zkq/wechat_flutter-master/ios/Pods/TXIMSDK_iOS/ImSDK.framework/ImSDK' for architecture arm64

Could not build the application for the simulator.
Error launching application on iPhone 13 Pro Max. 模拟器运行报错这个怎么解决呢？
