### ISSUE TITLE
[Discussions] 会不会有版权&专利问题

### ISSUE THREAD

**Issue by kant-li** [fluttercandies/wechat_flutter#53]
### Content

1. 项目依赖所用的开源协议会不会和 Apache 2.0 冲突？
2. UI界面和微信基本一致，个人甚至公司使用会不会有版权或专利问题？
3. 使用的其他声音、图像资源（如提示音、表情包、icon等）会不会有版权问题？

**Comment by ahyangnb** [comment]
腾讯云im官方知悉本项目并给予支持，在开源过程应该不会有涉及版权专利，但商用可能会有，如果修改表情和素材图的话就不会有什么问题。页面样式在市面上基本都是这样的，也没出现过被腾讯诉讼过的情况。

**Comment by kant-li** [comment]
好的，多谢！
